### ISSUE TITLE
Issue when sending issues on any version of library-ironic

### ISSUE THREAD

**Issue by Xstar97** [HeinrichReimer/android-issue-reporter#51]
STACK-TRACE:

java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.support.design.widget.TextInputLayout

--------- Stack trace ---------

```
com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.removeError(IssueReporterActivity.java:273)
com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.validateInput(IssueReporterActivity.java:254)
com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.reportIssue(IssueReporterActivity.java:200)
com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.access$100(IssueReporterActivity.java:52)
com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity$5.onClick(IssueReporterActivity.java:193)
android.view.View.performClick(View.java:4799)
android.view.View$PerformClick.run(View.java:20042)
android.os.Handler.handleCallback(Handler.java:739)
android.os.Handler.dispatchMessage(Handler.java:95)
android.os.Looper.loop(Looper.java:135)
android.app.ActivityThread.main(ActivityThread.java:5422)
java.lang.reflect.Method.invoke(Native Method)
java.lang.reflect.Method.invoke(Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

---

--------- Cause ---------

---

**Comment by Xstar97** [comment]
@HeinrichReimer this is a serious issue(for me) since none of my users can contact me about their issues...I really need some feedback about my issue....if you want to see how I implemented the library then just ask.

**Comment by HeinrichReimer** [comment]
Could you creeate a pull request with a fix?

**Comment by Xstar97** [comment]
Okay..i skimmed your code before & you have a lot of try catch exception with ClassCastException... I will clone your library & to see which one needs to be modified. At the moment I don't have my PC, but I will do it later today.

**Comment by Xstar97** [comment]
okay, I downloaded your source & updated the gradle files since they were outdated...however the following library is outdated:
    compile 'com.melnykov:floatingactionbutton:1.3.0'

when ever I tapped the FAB in my app it just crashes, but when I launch your sample with the library it works...I am going to re add your library to a blank app to see if crash will repeat itself....also are you working on any major/minor features?

**Comment by HeinrichReimer** [comment]
Ok, maybe wr should switch to the official Android support library FAB. I'll check that later today.

**Comment by pinpong** [comment]
I can confirm the issue.

**Comment by pinpong** [comment]
Should be fixed with latest commits.

**Comment by EvoWizz** [comment]
Hi, I have the exact same issue:
```
E/UncaughtException: java.lang.ClassCastException: android.widget.FrameLayout cannot be cast to android.support.design.widget.TextInputLayout
                                                                                  at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.setError(IssueReporterActivity.java:268)
                                                                                  at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.validateInput(IssueReporterActivity.java:225)
                                                                                  at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.reportIssue(IssueReporterActivity.java:200)
                                                                                  at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity.access$100(IssueReporterActivity.java:52)
                                                                                  at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity$5.onClick(IssueReporterActivity.java:193)
                                                                                  at android.view.View.performClick(View.java:5637)
                                                                                  at android.view.View$PerformClick.run(View.java:22433)
                                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

The version I've used is the v1.2.6 :/ 
Any ideas ?

**Comment by pinpong** [comment]
@EvoWizz try

`    compile 'com.heinrichreimersoftware:android-issue-reporter:eae4c73cbeb91e98da83fe79a3dea088a8b97448'
`

**Comment by EvoWizz** [comment]
@pinpong Working :)
