### ISSUE TITLE
Unable to send report with account login

### ISSUE THREAD

**Issue by pinpong** [HeinrichReimer/android-issue-reporter#56]
```
01-15 14:58:26.255 32357-32576/com.iotatoken.wallet W/System.err: java.io.IOException: Temporary Redirect (307)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:564)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:666)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at org.eclipse.egit.github.core.service.IssueService.createIssue(IssueService.java:634)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity$ReportIssueTask.doInBackground(IssueReporterActivity.java:382)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at com.heinrichreimersoftware.androidissuereporter.IssueReporterActivity$ReportIssueTask.doInBackground(IssueReporterActivity.java:343)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:305)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-15 14:58:26.256 32357-32576/com.iotatoken.wallet W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
01-15 14:58:26.257 32357-32576/com.iotatoken.wallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-15 14:58:26.257 32357-32576/com.iotatoken.wallet W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-15 14:58:26.257 32357-32576/com.iotatoken.wallet W/System.err:     at java.lang.Thread.run(Thread.java:761)
01-15 14:58:26.388 32357-32357/com.iotatoken.wallet W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
```

**Comment by HeinrichReimer** [comment]
It says there is a temporary redirect. 
Could possibly be that the URL is wrong or that you are using two-factor-authentication with your account.

**Comment by pinpong** [comment]
It was a wrong url but maybe its useful to add this info with the 2-factor-auth to readme.

**Comment by HeinrichReimer** [comment]
You are right! I should add that to the readme.
